apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-eks-iam-auth-controller
  namespace: flux-system
spec:
  interval: 1h
  url: https://rustrial.github.io/aws-eks-iam-auth-controller
