## Controller that combines IAMIdentityMapping into single aws-auth
## ConfigMap.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
