## Kubernetes AWS EFS CSI driver

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - storageclass-dynamic.yaml
  - storageclass-static.yaml
