apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: efs-demo
  namespace: efs-demo
spec:
  selector:
    matchLabels:
      app: efs-demo
  serviceName: efs-app
  replicas: 3
  template:
    metadata:
      labels:
        app: efs-demo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: alpine
          image: alpine
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do echo $(date -u) >> /efs-data/out.txt; sleep 5; done",
            ]
          volumeMounts:
            - name: efs-data
              mountPath: /efs-data
      volumes:
        - name: efs-data
          persistentVolumeClaim:
            claimName: efs
