## This file can't be generated by Flux using cluster-vars ConfigMap

resource "null_resource" "flux_ocirepository" {
  triggers = {
    cluster_context            = local.cluster_context
    flux_system_repository_url = local.flux_system_repository_url
  }

  provisioner "local-exec" {
    command = "kubectl delete ocirepository -n flux-system flux-system --ignore-not-found --kubeconfig .kube/config --context ${self.triggers.cluster_context} && flux create source oci flux-system --url=oci://${local.flux_system_repository_url} --tag=latest --provider=aws --kubeconfig .kube/config --context ${local.cluster_context}"
  }

  provisioner "local-exec" {
    when    = destroy
    command = "kubectl delete ocirepository -n flux-system flux-system --ignore-not-found --kubeconfig .kube/config --context ${self.triggers.cluster_context}"
  }

  depends_on = [
    null_resource.aws_eks_update-kubeconfig_terraform,
    null_resource.flux_bootstrap,
  ]
}
