## This file can't be generated by Flux using cluster-vars ConfigMap

resource "local_file" "flux_ocirepository" {
  content = templatefile("flux/flux-system/ocirepository.yaml.tftpl", {
    flux_system_repository_url = local.flux_system_repository_url
  })
  filename             = "flux/flux-system/ocirepository.yaml"
  directory_permission = "0755"
  file_permission      = "0644"
}
