## ConfigMap for AWS vpc-cni addon
##
## Terraform manages vpc-cni addon and settings for Linux. Windows nodes use
## ConfigMap rather than Env settings then all settings from
## `eks_addons/vpc-cni.configuration.yaml` must be defined here too.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
