apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  maxHistory: 2
  releaseName: metrics-server
  targetNamespace: kube-system
  storageNamespace: kube-system
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2 ## $ curl -qsS https://kubernetes-sigs.github.io/metrics-server/index.yaml | yq .entries.metrics-server.0.version
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      reconcileStrategy: ChartVersion
  values:
    ## https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
    containerPort: 10301
    hostNetwork:
      enabled: true
    replicas: 2
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: metrics-server
                  app.kubernetes.io/instance: metrics-server
              namespaces:
                - kube-system
              topologyKey: kubernetes.io/hostname
            weight: 1
