apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-demo
  namespace: efs-static-demo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-static
  resources:
    requests:
      storage: 5Gi
