apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-demo
  namespace: efs-static-demo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-static
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs_static_id}
  mountOptions:
    - iam
