# yaml-language-server: $schema=./coredns.schema.json

## https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html
## $ aws eks describe-addon-configuration --addon-name coredns --addon-version v1.11.3-eksbuild.2 | jq -r .configurationSchema | jq . > coredns.schema.json

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              eks.amazonaws.com/component: coredns
              k8s-app: kube-dns
          namespaces:
            - kube-system
          topologyKey: kubernetes.io/hostname
        weight: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
