# yaml-language-server: $schema=./eks-pod-identity-agent.schema.json

## $ aws eks describe-addon-configuration --addon-name eks-pod-identity-agent --addon-version v1.2.0-eksbuild.1 | jq -r .configurationSchema | jq . > eks_addons/eks-pod-identity-agent.schema.json

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

tolerations:
  - operator: Exists
