# yaml-language-server: $schema=./kube-proxy.schema.json

## aws eks describe-addon-configuration --addon-name kube-proxy --addon-version v1.24.10-eksbuild.2 | jq -r .configurationSchema | jq . > eks_addons/kube-proxy.schema.json

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
