# yaml-language-server: $schema=./vpc-cni.schema.json

## https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html
## $ aws eks describe-addon-configuration --addon-name vpc-cni --addon-version v1.18.5-eksbuild.1 | jq -r .configurationSchema | jq . > vpc-cni.schema.json

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
