apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: test
spec:
  subnetSelector:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  securityGroupSelector:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  amiFamily: Bottlerocket
  # amiSelector:
  #   aws::owners: amazon
  #   ## $ aws --region eu-central-1 ec2 describe-images --owners amazon --filters "Name=name,Values=bottlerocket-aws-k8s-1.25-x86_64-*" --query 'reverse(sort_by(Images, &Name))[0].Name' --output text | cat
  #   aws::name: bottlerocket-aws-k8s-1.25-x86_64-v1.15.1-264e294c
  tags:
    # AmiName: bottlerocket-aws-k8s-1.25-x86_64-v1.15.1-264e294c
    Cluster: {{ .Values.cluster_name }}
    Name: {{ .Values.cluster_name }}-test
    Nodegroup: test
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    ## boot nvme0n1
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        # iops: 3000
        # throughput: 125
        encrypted: true
        kmsKeyID: "arn:aws:kms:{{ .Values.region }}:{{ .Values.account_id }}:alias/aws/ebs"
        deleteOnTermination: true
    ## local nvme1n1
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        # iops: 3000
        # throughput: 125
        encrypted: true
        kmsKeyID: "arn:aws:kms:{{ .Values.region }}:{{ .Values.account_id }}:alias/aws/ebs"
        deleteOnTermination: true
  userData: |-
    [settings.host-containers.admin]
    enabled = true
    [settings.kubernetes]
    registry-qps = 0
    [settings.bootstrap-containers.bootstrap]
    source = "public.ecr.aws/stefansundin/bottlerocket-bootstrap-exec-user-data:latest"
    mode = "always"
    essential = false
    user-data = "{{ .Files.Get "bootstrap/test.sh" | b64enc }}"
  detailedMonitoring: true
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test
spec:
  providerRef:
    name: test
  labels:
    nodegroup: test
    nodegroup/test: "true"
  taints:
    - key: nodegroup/test
      value: "true"
      effect: NoSchedule
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - m5d
        - m6id
    # - key: karpenter.k8s.aws/instance-size
    #   operator: In
    #   values:
    #     - metal
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        # - arm64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
  kubeletConfiguration:
    clusterDNS:
      - {{ .Values.cluster_dns_ip }}
    containerRuntime: containerd
    # maxPods: 29
  # limits:
  #   resources:
  #     cpu: 10k
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 3600
  weight: 1
