apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: ubuntu
spec:
  subnetSelector:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  securityGroupSelector:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  amiFamily: Ubuntu
  tags:
    Cluster: {{ .Values.cluster_name }}
    Name: {{ .Values.cluster_name }}-ubuntu
    Nodegroup: ubuntu
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    ## boot nvme0n1
    - deviceName: /dev/sda1
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        # iops: 3000
        # throughput: 125
        encrypted: true
        kmsKeyID: "arn:aws:kms:{{ .Values.region }}:{{ .Values.account_id }}:alias/aws/ebs"
        deleteOnTermination: true
  detailedMonitoring: true
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: ubuntu
spec:
  providerRef:
    name: ubuntu
  labels:
    nodegroup: ubuntu
    nodegroup/ubuntu: "true"
  taints:
    - key: nodegroup/ubuntu
      value: "true"
      effect: NoSchedule
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - m5d
        - m6id
    # - key: karpenter.k8s.aws/instance-size
    #   operator: In
    #   values:
    #     - metal
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        # - arm64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
  kubeletConfiguration:
    clusterDNS:
      - {{ .Values.cluster_dns_ip }}
    containerRuntime: containerd
    maxPods: 18
  # limits:
  #   resources:
  #     cpu: 10k
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 3600
  weight: 1
---
{{- template "daemonset.aws-node" (dict "nodegroup" "ubuntu" "maxPods" 18) }}
