## Karpenter autoscaler. It starts on the nodes with CriticalAddonsOnly
## toleration only.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - helmrelease.yaml
