apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  type: oci
  provider: aws
  interval: 1h
  url: oci://public.ecr.aws/karpenter
