apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 1m
  timeout: 2m
  maxHistory: 2
  driftDetection:
    mode: enabled
  releaseName: karpenter
  targetNamespace: kube-system
  storageNamespace: kube-system
  serviceAccountName: helm-controller
  chart:
    spec:
      interval: 1m
      chart: karpenter
      version: 1.0.8 ## $ crane ls public.ecr.aws/karpenter/karpenter | sort -r -V | grep '^[0-9]*\.' | head -n1
      sourceRef:
        kind: HelmRepository
        name: karpenter
      reconcileStrategy: ChartVersion
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    ## https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml

    nodeSelector:
      nodegroup/critical: "true"

    controller:
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 1Gi

    logLevel: debug

    settings:
      clusterName: ${cluster_name}
      clusterEndpoint: https://${cluster_endpoint}
      isolatedVPC: false
      interruptionQueue: ${cluster_name}-karpenter
      reservedENIs: "0"

    webhook:
      enabled: false
