apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 1m
  timeout: 5m
  maxHistory: 2
  releaseName: podinfo
  targetNamespace: podinfo
  storageNamespace: podinfo
  driftDetection:
    mode: enabled
  chart:
    spec:
      interval: 1m
      chart: podinfo
      version: 6.4.1 ## curl -qsS https://stefanprodan.github.io/podinfo/index.yaml | yq .entries.podinfo.0.version
      sourceRef:
        kind: HelmRepository
        name: podinfo
      reconcileStrategy: ChartVersion
  values:
    ## https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml

    hpa:
      enabled: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
      hosts:
        - paths:
            - path: /
              pathType: Prefix

    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - podinfo
            topologyKey: kubernetes.io/hostname
