apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m
  timeout: 5m
  maxHistory: 2
  releaseName: podinfo
  targetNamespace: podinfo
  storageNamespace: podinfo
  driftDetection:
    mode: enabled
  chart:
    spec:
      interval: 1m
      chart: podinfo
      version: 6.4.1 ## curl -qsS https://stefanprodan.github.io/podinfo/index.yaml | yq .entries.podinfo.0.version
      sourceRef:
        kind: HelmRepository
        name: podinfo
      reconcileStrategy: ChartVersion
  values:
    ## https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml

    service:
      ## For Ingress with `target-type: instance`
      type: NodePort

    hpa:
      enabled: false

    ingress:
      enabled: true
      annotations:
        ## Name of the ALB
        alb.ingress.kubernetes.io/group.name: ${cluster_name}-ingress
        ## Name of the ALB
        alb.ingress.kubernetes.io/load-balancer-name: ${cluster_name}-ingress
        ## Must be the same as in `aws_lb.ingress.internal`
        alb.ingress.kubernetes.io/scheme: internet-facing
        ## `instance` for NodePort, `ip` for ClusterIP (then needs direct connection to Pod's IP)
        alb.ingress.kubernetes.io/target-type: instance
        ## WAF is enabled
        alb.ingress.kubernetes.io/wafv2-acl-arn: ${wafv2_acl_arn}
        ## Uses AWS Load Balancer Controller
        kubernetes.io/ingress.class: alb
      hosts:
        - paths:
            - path: /
              pathType: Prefix

    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - podinfo
            topologyKey: kubernetes.io/hostname
