apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-demo
  namespace: efs-dynamic-demo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic
  resources:
    requests:
      storage: 5Gi
