## FluxCD application with the namespaces and resource for the aws-auth.

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-auth
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /flux/aws-auth
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
