## FluxCD critical services that must be installed before other infrastructure.

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: critical
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /flux/critical
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
