## FluxCD critical services that must be installed before other infrastructure.

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: critical
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /flux/critical
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: aws-load-balancer-controller
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: eks-pod-identity-agent
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: karpenter
      namespace: flux-system
  timeout: 5m
