apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux-system
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
