apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - all.yaml
  - aws-load-balancer-controller.yaml
  - cluster-autoscaler.yaml
  - flux-system.yaml
  - podinfo.yaml
