## FluxCD application for networking resources in the Kubernetes
## cluster.
##
## It defines substituted variables that can be used in the base directory.

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  dependsOn:
    - name: critical
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /flux/networking
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: flux-system
  timeout: 5m
