## FluxCD application for nodepools.
##
## It defines substituted variables that can be used in the base directory.

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodepools
  namespace: flux-system
spec:
  dependsOn:
    - name: critical
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /flux/nodepools
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
