apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  dependsOn:
    - name: aws-load-balancer-controller
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./podinfo
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
